# Generated by Django 5.2.4 on 2025-08-06 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MotivationalQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(choices=[('kickboxing', 'Kickboxing Heavybag'), ('power_yoga', 'Power Yoga'), ('calisthenics', 'Calisthenics')], max_length=15)),
                ('quote_text', models.TextField(help_text="The content inside [...] brackets (without 'Remember, ')")),
                ('context', models.CharField(choices=[('warmup', 'During Warm-up'), ('intense', 'High Intensity Moments'), ('transition', 'Between Workout Parts'), ('cooldown', 'Cool Down'), ('anytime', 'Any Time')], default='anytime', max_length=15)),
                ('language', models.CharField(choices=[('nl', 'Dutch'), ('en', 'English')], default='nl', max_length=2)),
                ('times_used', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Motivational Quote',
                'verbose_name_plural': 'Motivational Quotes',
                'ordering': ['training_type', 'context'],
            },
        ),
        migrations.CreateModel(
            name='ScriptCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal name (e.g., 'kb_footwork')", max_length=50)),
                ('display_name', models.CharField(help_text="Display name (e.g., 'Footwork Training')", max_length=100)),
                ('training_type', models.CharField(choices=[('kickboxing', 'Kickboxing Heavybag'), ('power_yoga', 'Power Yoga'), ('calisthenics', 'Calisthenics')], max_length=15)),
                ('description', models.TextField(blank=True, help_text='What this section is for')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Script Category',
                'verbose_name_plural': 'Script Categories',
                'ordering': ['training_type', 'display_name'],
                'unique_together': {('name', 'training_type')},
            },
        ),
        migrations.CreateModel(
            name='WorkoutScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('kickboxing', 'Kickboxing Heavybag'), ('power_yoga', 'Power Yoga'), ('calisthenics', 'Calisthenics')], db_index=True, max_length=15)),
                ('goal', models.CharField(choices=[('allround', 'All-round'), ('endurance', 'Endurance'), ('strength', 'Strength'), ('flexibility', 'Flexibility'), ('technique', 'Technique')], db_index=True, max_length=15)),
                ('content', models.TextField(help_text='Script content with [pause strong]/[pause weak] markers')),
                ('duration_minutes', models.FloatField(help_text='Duration when spoken (e.g., 8.5 for 8:30)')),
                ('language', models.CharField(choices=[('nl', 'Dutch'), ('en', 'English')], default='nl', max_length=2)),
                ('times_selected', models.IntegerField(default=0, help_text='For engine variety logic')),
                ('last_selected', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes for Johnny')),
                ('script_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.scriptcategory')),
            ],
            options={
                'verbose_name': 'Workout Script',
                'verbose_name_plural': 'Workout Scripts',
                'ordering': ['type', 'script_category__display_name', 'title'],
                'indexes': [models.Index(fields=['type', 'script_category', 'goal'], name='scripts_wor_type_7473e8_idx'), models.Index(fields=['times_selected', 'last_selected'], name='scripts_wor_times_s_44af35_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkoutTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(choices=[('kickboxing', 'Kickboxing Heavybag'), ('power_yoga', 'Power Yoga'), ('calisthenics', 'Calisthenics')], max_length=15)),
                ('sequence_order', models.IntegerField()),
                ('is_required', models.BooleanField(default=True, help_text='Must be included in every workout')),
                ('min_duration', models.FloatField(blank=True, null=True)),
                ('max_duration', models.FloatField(blank=True, null=True)),
                ('preferred_duration', models.FloatField(blank=True, help_text='Ideal duration for this part', null=True)),
                ('alternative_categories', models.ManyToManyField(blank=True, help_text="Alternative categories for OR logic (e.g., 'just combos' as alternative to 'combo building')", related_name='alternative_templates', to='scripts.scriptcategory')),
                ('primary_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_templates', to='scripts.scriptcategory')),
            ],
            options={
                'verbose_name': 'Workout Template',
                'verbose_name_plural': 'Workout Templates',
                'ordering': ['training_type', 'sequence_order'],
                'unique_together': {('training_type', 'sequence_order')},
            },
        ),
    ]
