# Generated by Django 5.2.4 on 2025-08-08 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scriptcategory',
            options={'ordering': ['training_type', 'difficulty_level', 'display_name'], 'verbose_name': 'Script Category', 'verbose_name_plural': 'Script Categories'},
        ),
        migrations.AlterModelOptions(
            name='workouttemplate',
            options={'ordering': ['training_type', 'sequence_order', 'sequence_priority'], 'verbose_name': 'Workout Template', 'verbose_name_plural': 'Workout Templates'},
        ),
        migrations.AddField(
            model_name='scriptcategory',
            name='difficulty_level',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1, help_text='How hard this section is - helps order exercises properly'),
        ),
        migrations.AddField(
            model_name='scriptcategory',
            name='must_be_last',
            field=models.BooleanField(default=False, help_text='Always put this at the end (like MAX Challenge)'),
        ),
        migrations.AddField(
            model_name='scriptcategory',
            name='sport_specific_rules',
            field=models.JSONField(blank=True, default=dict, help_text='Special rules for this category - usually left empty'),
        ),
        migrations.AddField(
            model_name='workoutscript',
            name='intensity_level',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2, help_text='How intense this script is - helps with flow decisions'),
        ),
        migrations.AddField(
            model_name='workoutscript',
            name='transition_type',
            field=models.CharField(choices=[('standing_to_standing', 'Standing to Standing'), ('standing_to_sitting', 'Standing to Sitting'), ('sitting_to_standing', 'Sitting to Standing'), ('flow_transition', 'General Flow'), ('none', 'No Transition')], default='none', help_text='What kind of position change this provides (for yoga)', max_length=20),
        ),
        migrations.AddField(
            model_name='workouttemplate',
            name='requires_surprise_round',
            field=models.BooleanField(default=False, help_text='Add a surprise round after this section (kickboxing only)'),
        ),
        migrations.AddField(
            model_name='workouttemplate',
            name='requires_transition',
            field=models.BooleanField(default=False, help_text='Check if transition needed after this section (yoga flow)'),
        ),
        migrations.AddField(
            model_name='workouttemplate',
            name='sequence_priority',
            field=models.IntegerField(default=0, help_text='Force certain order despite sequence_order (higher = later)'),
        ),
        migrations.AddField(
            model_name='workouttemplate',
            name='transition_script_category',
            field=models.ForeignKey(blank=True, help_text='Which transition type to use (for yoga vinyasa)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transition_templates', to='scripts.scriptcategory'),
        ),
        migrations.AlterField(
            model_name='motivationalquote',
            name='context',
            field=models.CharField(choices=[('warmup', 'During Warm-up'), ('intense', 'High Intensity Moments'), ('transition', 'Between Workout Parts'), ('cooldown', 'Cool Down'), ('anytime', 'Any Time')], default='anytime', help_text='When to use this quote during workouts', max_length=15),
        ),
        migrations.AlterField(
            model_name='motivationalquote',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Turn off to hide this quote without deleting it'),
        ),
        migrations.AlterField(
            model_name='motivationalquote',
            name='language',
            field=models.CharField(choices=[('nl', 'Dutch'), ('en', 'English')], default='nl', help_text='Language for this quote', max_length=2),
        ),
        migrations.AlterField(
            model_name='motivationalquote',
            name='last_used',
            field=models.DateTimeField(blank=True, help_text='When this quote was last used - system tracks automatically', null=True),
        ),
        migrations.AlterField(
            model_name='motivationalquote',
            name='quote_text',
            field=models.TextField(help_text="The motivational text - 'Onthoud,' will be added automatically"),
        ),
        migrations.AlterField(
            model_name='motivationalquote',
            name='times_used',
            field=models.IntegerField(default=0, help_text='How often this quote was used - system tracks automatically'),
        ),
        migrations.AlterField(
            model_name='motivationalquote',
            name='training_type',
            field=models.CharField(choices=[('kickboxing', 'Kickboxing Heavybag'), ('power_yoga', 'Power Yoga'), ('calisthenics', 'Calisthenics')], help_text='Which sport this motivational quote is for', max_length=15),
        ),
        migrations.AlterField(
            model_name='scriptcategory',
            name='description',
            field=models.TextField(blank=True, help_text='What this section is for - helps you organize your content'),
        ),
        migrations.AlterField(
            model_name='scriptcategory',
            name='display_name',
            field=models.CharField(help_text="The name you see in workouts (e.g., 'Footwork Training')", max_length=100),
        ),
        migrations.AlterField(
            model_name='scriptcategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Turn off to hide this category without deleting it'),
        ),
        migrations.AlterField(
            model_name='scriptcategory',
            name='name',
            field=models.CharField(help_text="System name - don't change this once created", max_length=50),
        ),
        migrations.AlterField(
            model_name='workoutscript',
            name='content',
            field=models.TextField(help_text='The actual script text with [pause strong]/[pause weak] markers'),
        ),
        migrations.AlterField(
            model_name='workoutscript',
            name='duration_minutes',
            field=models.FloatField(help_text='How long this takes to speak (from murf.ai timing)'),
        ),
        migrations.AlterField(
            model_name='workoutscript',
            name='goal',
            field=models.CharField(choices=[('allround', 'All-round'), ('endurance', 'Endurance'), ('strength', 'Strength'), ('flexibility', 'Flexibility'), ('technique', 'Technique')], db_index=True, help_text='What fitness goal this targets', max_length=15),
        ),
        migrations.AlterField(
            model_name='workoutscript',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Turn off to hide this script without deleting it'),
        ),
        migrations.AlterField(
            model_name='workoutscript',
            name='language',
            field=models.CharField(choices=[('nl', 'Dutch'), ('en', 'English')], default='nl', help_text='Language for this script', max_length=2),
        ),
        migrations.AlterField(
            model_name='workoutscript',
            name='last_selected',
            field=models.DateTimeField(blank=True, help_text='When this was last used - system tracks automatically', null=True),
        ),
        migrations.AlterField(
            model_name='workoutscript',
            name='notes',
            field=models.TextField(blank=True, help_text='Your personal notes about this script'),
        ),
        migrations.AlterField(
            model_name='workoutscript',
            name='script_category',
            field=models.ForeignKey(help_text='What type of exercise this is (warmup, combos, etc.)', on_delete=django.db.models.deletion.CASCADE, to='scripts.scriptcategory'),
        ),
        migrations.AlterField(
            model_name='workoutscript',
            name='times_selected',
            field=models.IntegerField(default=0, help_text='How often this was used - system tracks automatically'),
        ),
        migrations.AlterField(
            model_name='workoutscript',
            name='title',
            field=models.CharField(help_text="Name for this script - 'Round 1:' will be removed automatically", max_length=200),
        ),
        migrations.AlterField(
            model_name='workoutscript',
            name='type',
            field=models.CharField(choices=[('kickboxing', 'Kickboxing Heavybag'), ('power_yoga', 'Power Yoga'), ('calisthenics', 'Calisthenics')], db_index=True, help_text='Which sport this script is for', max_length=15),
        ),
        migrations.AlterField(
            model_name='workouttemplate',
            name='alternative_categories',
            field=models.ManyToManyField(blank=True, help_text='Other exercise types that can be used instead (creates choice)', related_name='alternative_templates', to='scripts.scriptcategory'),
        ),
        migrations.AlterField(
            model_name='workouttemplate',
            name='is_required',
            field=models.BooleanField(default=True, help_text='Must be included in every workout (turn off for optional sections)'),
        ),
        migrations.AlterField(
            model_name='workouttemplate',
            name='max_duration',
            field=models.FloatField(blank=True, help_text='Maximum time for this section in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='workouttemplate',
            name='min_duration',
            field=models.FloatField(blank=True, help_text='Minimum time for this section in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='workouttemplate',
            name='preferred_duration',
            field=models.FloatField(blank=True, help_text='Ideal time for this section in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='workouttemplate',
            name='primary_category',
            field=models.ForeignKey(help_text='Main type of exercise for this step', on_delete=django.db.models.deletion.CASCADE, related_name='primary_templates', to='scripts.scriptcategory'),
        ),
        migrations.AlterField(
            model_name='workouttemplate',
            name='sequence_order',
            field=models.IntegerField(help_text='Order in workout (1 = first, 2 = second, etc.)'),
        ),
        migrations.AlterField(
            model_name='workouttemplate',
            name='training_type',
            field=models.CharField(choices=[('kickboxing', 'Kickboxing Heavybag'), ('power_yoga', 'Power Yoga'), ('calisthenics', 'Calisthenics')], help_text='Which sport this template is for', max_length=15),
        ),
        migrations.AddIndex(
            model_name='workoutscript',
            index=models.Index(fields=['intensity_level', 'transition_type'], name='scripts_wor_intensi_495cdd_idx'),
        ),
    ]
