# Generated by Django 5.2.4 on 2025-08-16 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_alter_scriptcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motivationalquote',
            options={'ordering': ['training_type', 'is_exercise_specific', 'target_category'], 'verbose_name': 'Motivational Quote', 'verbose_name_plural': 'Motivational Quotes'},
        ),
        migrations.RemoveField(
            model_name='motivationalquote',
            name='context',
        ),
        migrations.AddField(
            model_name='motivationalquote',
            name='is_exercise_specific',
            field=models.BooleanField(default=False, help_text='Only use during the selected exercise category'),
        ),
        migrations.AddField(
            model_name='motivationalquote',
            name='target_category',
            field=models.ForeignKey(blank=True, help_text='Specific exercise category (leave blank for general quotes)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specific_quotes', to='scripts.scriptcategory'),
        ),
        migrations.AlterField(
            model_name='workoutscript',
            name='duration_minutes',
            field=models.FloatField(help_text='How long this takes to speak'),
        ),
    ]
