# Generated by Django 5.2.4 on 2025-08-18 07:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0003_alter_motivationalquote_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scriptcategory',
            options={'ordering': ['training_type', 'display_name'], 'verbose_name': 'Script Category', 'verbose_name_plural': 'Script Categories'},
        ),
        migrations.AlterModelOptions(
            name='workouttemplate',
            options={'ordering': ['training_type', 'sequence_order'], 'verbose_name': 'Workout Template', 'verbose_name_plural': 'Workout Templates'},
        ),
        migrations.RemoveIndex(
            model_name='workoutscript',
            name='scripts_wor_intensi_495cdd_idx',
        ),
        migrations.RemoveField(
            model_name='scriptcategory',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='scriptcategory',
            name='must_be_last',
        ),
        migrations.RemoveField(
            model_name='scriptcategory',
            name='sport_specific_rules',
        ),
        migrations.RemoveField(
            model_name='workoutscript',
            name='intensity_level',
        ),
        migrations.RemoveField(
            model_name='workoutscript',
            name='transition_type',
        ),
        migrations.RemoveField(
            model_name='workouttemplate',
            name='requires_surprise_round',
        ),
        migrations.RemoveField(
            model_name='workouttemplate',
            name='requires_transition',
        ),
        migrations.RemoveField(
            model_name='workouttemplate',
            name='sequence_priority',
        ),
        migrations.RemoveField(
            model_name='workouttemplate',
            name='transition_script_category',
        ),
        migrations.AddField(
            model_name='workouttemplate',
            name='add_max_challenge_after',
            field=models.BooleanField(default=False, help_text='Add a MAX challenge after this step (system will auto-find MAX challenge category)'),
        ),
        migrations.AddField(
            model_name='workouttemplate',
            name='add_surprise_round_after',
            field=models.BooleanField(default=False, help_text='Add a surprise round after this step (system will auto-find surprise category)'),
        ),
        migrations.AddField(
            model_name='workouttemplate',
            name='add_vinyasa_transition_after',
            field=models.BooleanField(default=False, help_text='Add a vinyasa transition after this step (system will auto-find vinyasa category)'),
        ),
        migrations.AddField(
            model_name='workouttemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 18, 7, 39, 48, 769241, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workouttemplate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Turn off to disable this template step without deleting it'),
        ),
        migrations.AddField(
            model_name='workouttemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workouttemplate',
            name='vinyasa_type',
            field=models.CharField(blank=True, choices=[('standing_to_standing', 'Standing to Standing'), ('standing_to_sitting', 'Standing to Sitting')], help_text='Which type of vinyasa transition (system will auto-find matching category)', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='scriptcategory',
            name='description',
            field=models.TextField(blank=True, help_text='What this section is for'),
        ),
        migrations.AlterField(
            model_name='scriptcategory',
            name='display_name',
            field=models.CharField(help_text='The name you see in workouts', max_length=100),
        ),
        migrations.AlterField(
            model_name='scriptcategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Turn off to hide this category'),
        ),
        migrations.AlterField(
            model_name='workoutscript',
            name='duration_minutes',
            field=models.FloatField(help_text='How long this takes to speak in minutes'),
        ),
        migrations.AlterField(
            model_name='workoutscript',
            name='script_category',
            field=models.ForeignKey(help_text='What type of exercise this is (warmup, combos, surprise, etc.)', on_delete=django.db.models.deletion.CASCADE, to='scripts.scriptcategory'),
        ),
        migrations.AlterField(
            model_name='workouttemplate',
            name='alternative_categories',
            field=models.ManyToManyField(blank=True, help_text="Other exercise types that can be used instead (creates 'A OR B OR C' choice)", related_name='alternative_templates', to='scripts.scriptcategory'),
        ),
        migrations.AlterField(
            model_name='workouttemplate',
            name='is_required',
            field=models.BooleanField(default=True, help_text='Must be included in every workout (when this template step is active)'),
        ),
        migrations.AlterField(
            model_name='workouttemplate',
            name='max_duration',
            field=models.FloatField(blank=True, help_text='Maximum time for this section in minutes (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='workouttemplate',
            name='min_duration',
            field=models.FloatField(blank=True, help_text='Minimum time for this section in minutes (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='workouttemplate',
            name='preferred_duration',
            field=models.FloatField(blank=True, help_text='Ideal time for this section in minutes (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='workouttemplate',
            name='sequence_order',
            field=models.IntegerField(help_text='Order in workout (1 = first, 2 = second, etc.) - higher numbers come later'),
        ),
    ]
