# Generated by Django 5.2.4 on 2025-08-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0004_alter_scriptcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scriptcategory',
            options={'ordering': ['training_type', 'is_system_category', 'display_name'], 'verbose_name': 'Script Category', 'verbose_name_plural': 'Script Categories'},
        ),
        migrations.AddField(
            model_name='scriptcategory',
            name='is_system_category',
            field=models.BooleanField(default=False, help_text='System category - cannot be deleted, name cannot be changed'),
        ),
        migrations.AlterField(
            model_name='scriptcategory',
            name='display_name',
            field=models.CharField(help_text='Display name - can be customized even for system categories', max_length=100),
        ),
        migrations.AlterField(
            model_name='scriptcategory',
            name='name',
            field=models.CharField(help_text='System name - PROTECTED for system categories', max_length=50),
        ),
    ]
