# Generated by Django 5.2.4 on 2025-08-18 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0006_add_system_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scriptcategory',
            options={'ordering': ['training_type', 'display_name'], 'verbose_name': 'Script Category', 'verbose_name_plural': 'Script Categories'},
        ),
    ]
