# Generated by Django 5.2.4 on 2025-08-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0007_alter_scriptcategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutscript',
            name='duration_minutes',
            field=models.DecimalField(decimal_places=1, help_text='How long this takes to speak in minutes', max_digits=4),
        ),
        migrations.AlterField(
            model_name='workoutscript',
            name='goal',
            field=models.CharField(choices=[('allround', 'All-round'), ('strength', 'Strength'), ('flexibility', 'Flexibility')], db_index=True, help_text='What fitness goal this targets', max_length=15),
        ),
    ]
