# Generated by Django 5.2.4 on 2025-08-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0008_alter_workoutscript_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutscript',
            name='duration_minutes',
            field=models.FloatField(help_text='How long this takes to speak in minutes'),
        ),
    ]
