# Generated by Django 5.2.4 on 2025-08-06 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(choices=[('kickboxing', 'Kickboxing Heavybag'), ('power_yoga', 'Power Yoga'), ('calisthenics', 'Calisthenics')], max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('total_duration', models.FloatField()),
                ('target_duration', models.FloatField(default=60.0)),
                ('time_flexibility', models.FloatField(default=5.0)),
                ('goal', models.CharField(choices=[('allround', 'All-round'), ('endurance', 'Endurance'), ('strength', 'Strength'), ('flexibility', 'Flexibility'), ('technique', 'Technique')], max_length=15)),
                ('compiled_script', models.TextField(help_text='Final compiled script with motivational quotes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False, help_text='Did Johnny use this workout?')),
                ('notes', models.TextField(blank=True, help_text="Johnny's notes about this workout")),
            ],
            options={
                'verbose_name': 'Workout Session',
                'verbose_name_plural': 'Workout Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.IntegerField()),
                ('workout_script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.workoutscript')),
                ('workout_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_scripts', to='generator.workoutsession')),
            ],
            options={
                'verbose_name': 'Session Script',
                'verbose_name_plural': 'Session Scripts',
                'ordering': ['sequence_order'],
            },
        ),
    ]
