# Generated by Django 5.2.4 on 2025-08-08 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
        ('scripts', '0002_alter_scriptcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionscript',
            name='is_sport_addition',
            field=models.BooleanField(default=False, help_text='Added by sport intelligence (surprise round, vinyasa, etc.)'),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='sport_additions_applied',
            field=models.JSONField(default=dict, help_text='What sport-specific features were added automatically'),
        ),
        migrations.AlterField(
            model_name='sessionscript',
            name='sequence_order',
            field=models.IntegerField(help_text='Order in the workout (1 = first, 2 = second, etc.)'),
        ),
        migrations.AlterField(
            model_name='sessionscript',
            name='workout_script',
            field=models.ForeignKey(help_text='The actual script that was used', on_delete=django.db.models.deletion.CASCADE, to='scripts.workoutscript'),
        ),
        migrations.AlterField(
            model_name='sessionscript',
            name='workout_session',
            field=models.ForeignKey(help_text='Which workout session this script belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='session_scripts', to='generator.workoutsession'),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='compiled_script',
            field=models.TextField(help_text='Complete workout script ready for voice recording'),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='goal',
            field=models.CharField(choices=[('allround', 'All-round'), ('endurance', 'Endurance'), ('strength', 'Strength'), ('flexibility', 'Flexibility'), ('technique', 'Technique')], help_text='Fitness goal this workout targets', max_length=15),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='is_used',
            field=models.BooleanField(default=False, help_text='Check this after you record this workout'),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='notes',
            field=models.TextField(blank=True, help_text='Your notes about how this workout went'),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='target_duration',
            field=models.FloatField(default=60.0, help_text='Target time you wanted (usually 60 minutes)'),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='time_flexibility',
            field=models.FloatField(default=5.0, help_text='How many minutes off-target is acceptable (±5 minutes)'),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='title',
            field=models.CharField(help_text='Generated workout name with date and goal', max_length=200),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='total_duration',
            field=models.FloatField(help_text='Actual total time in minutes'),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='training_type',
            field=models.CharField(choices=[('kickboxing', 'Kickboxing Heavybag'), ('power_yoga', 'Power Yoga'), ('calisthenics', 'Calisthenics')], help_text='Which sport this workout is for', max_length=15),
        ),
    ]
