# Generated by Django 5.2.4 on 2025-08-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_sessionscript_is_sport_addition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsession',
            name='goal',
            field=models.CharField(choices=[('allround', 'All-round'), ('strength', 'Strength'), ('flexibility', 'Flexibility')], help_text='Fitness goal this workout targets', max_length=15),
        ),
    ]
